// This file is auto-generated by scripts/update-backend-ip.js
// Do not edit manually.
export const BACKEND_IP = require('../backend-ip.json').ip;
export const BACKEND_URL = `http://${BACKEND_IP}:8000`;
